name = "Zenarchist's Virus Mod"; // name
picture = "ZenVirus\data\zen_virus_thumbnail.edds"; // picture in expanded description
logoSmall = "ZenVirus\data\zen_virus_thumbnail.edds"; // icon next to mod name when description is not expanded
logo = "ZenVirus\data\zen_virus_thumbnail.edds"; // logo below game menu
logoOver = "ZenVirus\data\zen_virus_thumbnail.edds"; // on mouse hover over logo
tooltip = "Zenarchist's Virus Mod"; // tool tip on mouse hover
overview = "Adds a new zombie virus to the game."; // overview
action = "https://zenarchist.io/"; // link
author = "Zenarchist"; // author
version = "1.1"; // version